app:
  database-access-type: jpa
  scheduler:
    enable: true
    interval: "PT10M"
    force-check-delay: "PT60M"
  github-base-url:
    base-url: "https://api.github.com/repos/"
  stackoverflow-base-url:
    base-url: "https://api.stackexchange.com/2.3/questions/"
  bot-base-url:
    base-url: "http://localhost:8090"

api:
  bot:
    retry-policy: CONSTANT
    attempts: 3
    http-statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
  github:
    retry-policy: constant
    attempts: 3
    http-statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
  stackoverflow:
    retry-policy: constant
    attempts: 3
    http-statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT

spring:
  application:
    name: scrapper
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

bucket:
  count: 10
