app:
  telegram-token: ${TELEGRAM_TOKEN}
  scrapper-base-url:
    base-url: "http://localhost:8080"

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

api:
  scrapper:
    retry-policy: constant
    attempts: 3
    http-statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT

springdoc:
  swagger-ui:
    path: /swagger-ui

bucket:
  count: 10
